// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sample.proto

package sample;

public interface ProductIDOrBuilder extends
    // @@protoc_insertion_point(interface_extends:sample.ProductID)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  String getId();
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();
}
