// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sample.proto

package sample;

public final class Sample {
  private Sample() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_sample_ProductInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_sample_ProductInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_sample_ProductID_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_sample_ProductID_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\014sample.proto\022\006sample\"K\n\013ProductInfo\022\n\n" +
      "\002id\030\001 \001(\t\022\014\n\004name\030\002 \001(\t\022\023\n\013description\030\003" +
      " \001(\t\022\r\n\005price\030\004 \001(\005\"\027\n\tProductID\022\n\n\002id\030\001" +
      " \001(\t2\207\001\n\rSampleService\022:\n\016getProductInfo" +
      "\022\021.sample.ProductID\032\023.sample.ProductInfo" +
      "\"\000\022:\n\016addProductInfo\022\023.sample.ProductInf" +
      "o\032\021.sample.ProductID\"\000B\n\n\006sampleP\001b\006prot" +
      "o3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_sample_ProductInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_sample_ProductInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_sample_ProductInfo_descriptor,
        new String[] { "Id", "Name", "Description", "Price", });
    internal_static_sample_ProductID_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_sample_ProductID_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_sample_ProductID_descriptor,
        new String[] { "Id", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
